# IMPORTAMOS SYS PARA MANEJAR RUTAS
import sys
# -> IMPORTAMOS LOGGING PARA REGISTRAR LOS PROCESOS DE EXTRACCIÓN Y CONTROL DE EXTRACCIÓN.
import logging
# DESDE PATHLIB IMPORTAMOS Path PARA MANEJAR RUTAS DE MANERA MÁS SENCILLA Y 
# PORTABLE ENTRE SISTEMAS OPERATIVOS         
from pathlib import Path

# AGREGAMOS EL DIRECTORIO ACTUAL AL PATH PARA PODER IMPORTAR LOS MÓDULOS DE EXTRACCIÓN Y CONTROL
sys.path.append(str(Path(__file__).resolve().parent))

# DESDE CONFIG IMPORTAMOS SETTINGS PARA OBTENER LAS CONFIGURACIONES NECESARIAS PARA LA EXTRACCIÓN Y CONTROL DE EXTRACCIÓN 
from config import settings
# DESDE EXTRACCIÓN IMPORTAMOS OracleReader PARA REALIZAR LA EXTRACCIÓN DE DATOS DESDE ORACLE Y ControlExtracción PARA MANEJAR EL CONTROL DE EXTRACCIÓN EN SQLITE 
from extraccion.oracle_reader import OracleReader
# DESDE EXTRACCIÓN CONTROL IMPORTAMOS ControlExtracción PARA MANEJAR EL CONTROL DE EXTRACCIÓN EN SQLITE
from extraccion.control import ControlExtraccion
# -> DESDE TRANSFORMACIÓN IMPORTAMOS LimpiadorDatos PARA REALIZAR LA LIMPIEZA DE LOS DATOS EXTRAÍDOS ANTES DE GUARDARLOS EN CSV Y GENERAR LOS MANIFIESTOS.
from transformacion.limpieza import LimpiadorDatos
# -> DESDE CARGA IMPORTAMOS CSVWriter PARA GUARDAR LOS LOTES EN ARCHIVOS CSV Y GENERAR LOS MANIFIESTOS EN FORMATO JSON.
from carga.csv_writer import CSVWriter

"""
# ESTA FUNCIÓN SE ENCARGA DE EJECUTAR UNA PRUEBA DE EXTRACCIÓN PARA VERIFICAR QUE 
# TODO ESTÉ CONFIGURADO CORRECTAMENTE Y QUE SE PUEDAN EXTRAER LOS DATOS DE ORACLE 
# Y CONTROLAR LA EXTRACCIÓN CON SQLITE. IMPRIME LOS RESULTADOS DE CADA PASO PARA FACILITAR LA VERIFICACIÓN.     
def ejecutar_prueba():
    # IMPRIMIMOS UN MENSAJE INFORMATIVO PARA INDICAR QUE SE ESTÁ INICIANDO LA PRUEBA DE EXTRACCIÓN   
    print("--- INICIANDO PRUEBA DE EXTRACCIÓN ---")
    
    # CONTROL DE EXTRACCIÓN (SQLITE) - OBTENEMOS EL ÚLTIMO ID DE PACIENTES PARA SABER DESDE DÓNDE INICIAR LA EXTRACCIÓN EN ORACLE Y EVITAR DUPLICADOS  
    control = ControlExtraccion(settings.CONTROL_DB_PATH)
    # OBTENEMOS EL ÚLTIMO ID DE PACIENTES PARA SABER DESDE DÓNDE INICIAR LA EXTRACCIÓN EN ORACLE Y EVITAR DUPLICADOS 
    ultimo_id = control.obtener_ultimo_id("PACIENTES")
    # IMPRIMIMOS EL ÚLTIMO ID DE PACIENTES OBTENIDO PARA VERIFICAR QUE SE ESTÁ OBTENIENDO CORRECTAMENTE
    print(f"Último ID de PACIENTES en SQLite: {ultimo_id}")

    # EXTRACCIÓN (ORACLE) - PROBAMOS LA CONEXIÓN Y EXTRAEMOS UN LOTE PEQUEÑO DE DATOS PARA VERIFICAR QUE SE PUEDEN EXTRAER CORRECTAMENTE  
    reader = OracleReader(settings.ORACLE_DSN)
    # PROBAMOS LA CONEXIÓN A ORACLE PARA VERIFICAR QUE ESTÁ CONFIGURADA CORRECTAMENTE Y SE PUEDE CONECTAR A LA BASE DE DATOS ANTES DE INTENTAR EXTRAER LOS DATOS 
    reader.probar_conexion()
    
    # DF ES EL DATAFRAME RESULTANTE DE LA EXTRACCIÓN DE UN LOTE PEQUEÑO DE DATOS DE LA TABLA PACIENTES DESDE ORACLE, 
    # INICIANDO DESDE EL ÚLTIMO ID OBTENIDO EN SQLITE PARA EVITAR DUPLICADOS. SE IMPRIMEN LOS PRIMEROS 5 REGISTROS PARA 
    # VERIFICAR QUE SE ESTÁN EXTRAÍENDO LOS DATOS CORRECTAMENTE. SI NO SE ENCUENTRAN REGISTROS, SE IMPRIME UN MENSAJE 
    # INDICANDO QUE NO SE ENCONTRARON REGISTROS, LO CUAL PUEDE SER NORMAL SI EL SCRIPT SQL AÚN NO HA CARGADO LOS DATOS EN ORACLE. 
    df = reader.extraer_lote("PACIENTES", "paciente_id", ultimo_id, lote_size=5)
    
    # SI EL DATAFRAME NO ESTÁ VACÍO, IMPRIMIMOS UN MENSAJE DE ÉXITO Y LOS PRIMEROS 5 REGISTROS PARA VERIFICAR 
    # QUE SE ESTÁN EXTRAÍENDO LOS DATOS CORRECTAMENTE. SI EL DATAFRAME ESTÁ VACÍO, IMPRIMIMOS UN MENSAJE INDICANDO QUE 
    # NO SE ENCONTRARON REGISTROS, LO CUAL PUEDE SER NORMAL SI EL SCRIPT SQL AÚN NO HA CARGADO LOS DATOS EN ORACLE.  
    if not df.empty:
        # IMPRIMIMOS UN MENSAJE DE ÉXITO Y LOS PRIMEROS 5 REGISTROS PARA VERIFICAR QUE SE ESTÁN EXTRAYENDO LOS DATOS CORRECTAMENTE  
        print("\n¡Extracción Exitosa! Aquí están los primeros 5 registros:")
        # IMPRIMIMOS LOS PRIMEROS 5 REGISTROS DEL DATAFRAME PARA VERIFICAR QUE SE ESTÁN EXTRAÍENDO LOS DATOS CORRECTAMENTE. 
        # SELECCIONAMOS SOLO LAS COLUMNAS RELEVANTES PARA LA VERIFICACIÓN.
        print(df.head())
        #print(df[['PACIENTE_ID', 'NOMBRE', 'APELLIDO', 'DOCUMENTO_IDENTIDAD']])
    # SINO SE ENCONTRARON REGISTROS, IMPRIMIMOS UN MENSAJE INDICANDO QUE NO SE ENCONTRARON REGISTROS, 
    # LO CUAL PUEDE SER NORMAL SI EL SCRIPT SQL AÚN NO HA CARGADO LOS DATOS EN ORACLE.
    else:
        print("No se encontraron registros. (¿Terminó de cargar el script SQL en Docker?)")

# SI ESTE ARCHIVO SE EJECUTA DIRECTAMENTE, SE LLAMA A LA FUNCIÓN ejecutar_prueba() PARA REALIZAR LA PRUEBA DE EXTRACCIÓN. 
if __name__ == "__main__":
    ejecutar_prueba()
"""

# -> CÓDIGO ACTUALIZADO 

# ESTA FUNCIÓN SE ENCARGA DE EJECUTAR TODO EL PIPELINE ETL PARA LA TABLA PACIENTES, INCLUYENDO LA EXTRACCIÓN 
# DESDE ORACLE, LA TRANSFORMACIÓN DE LOS DATOS Y LA CARGA EN ARCHIVOS CSV, ASÍ COMO LA GENERACIÓN DE MANIFIESTOS 
# EN FORMATO JSON. REGISTRA CADA PASO DEL PROCESO EN EL LOG PARA FACILITAR EL SEGUIMIENTO Y LA VERIFICACIÓN DEL PROGRESO.  
def ejecutar_pipeline_completo():
    # IMPRIMIMOS UN MENSAJE INFORMATIVO PARA INDICAR QUE SE ESTÁ INICIANDO EL PIPELINE ETL PARA 
    # EL HOSPITAL Y QUE SE PROCESARÁN LOS DATOS DE LA TABLA PACIENTES.
    logging.info("=== INICIANDO PIPELINE ETL HOSPITAL ===")
    
    # INICIALIZAMOS LOS OBJETOS NECESARIOS PARA LA EXTRACCIÓN, CONTROL DE EXTRACCIÓN Y CARGA. 
    reader = OracleReader(settings.ORACLE_DSN)
    # CONTROL DE EXTRACCIÓN (SQLITE) - OBTENEMOS EL ÚLTIMO ID DE PACIENTES PARA SABER DESDE DÓNDE 
    # INICIAR LA EXTRACCIÓN EN ORACLE Y EVITAR DUPLICADOS    
    control = ControlExtraccion(settings.CONTROL_DB_PATH)
    # CSV WRITER - SE ENCARGA DE GUARDAR LOS LOTES EN ARCHIVOS CSV Y GENERAR LOS MANIFIESTOS EN FORMATO JSON. 
    # SE INICIALIZA CON LA RUTA DE SALIDA CONFIGURADA EN SETTINGS.
    writer = CSVWriter(settings.OUTPUT_DIR)
    
    # DEFINIMOS LAS VARIABLES NECESARIAS PARA CONTROLAR EL PROCESAMIENTO DE LA TABLA PACIENTES, INCLUYENDO 
    # EL NOMBRE DE LA TABLA, LA CLAVE PRIMARIA, EL TOTAL DE REGISTROS MIGRADOS, LA LISTA DE ARCHIVOS GENERADOS 
    # Y EL NÚMERO DE LOTE. ESTAS VARIABLES SE UTILIZARÁN A LO LARGO DEL PROCESO PARA CONTROLAR EL 
    # FLUJO DE EXTRACCIÓN, TRANSFORMACIÓN Y CARGA, ASÍ COMO PARA GENERAR LOS MANIFIESTOS CON LA INFORMACIÓN 
    # RELEVANTE SOBRE EL PROCESO DE MIGRACIÓN.  
    tabla = "PACIENTES"
    # CLAVE PRIMARIA DE LA TABLA PACIENTES, QUE SE UTILIZA PARA CONTROLAR LA EXTRACCIÓN Y EVITAR DUPLICADOS.
    pk = "paciente_id"
    # TOTAL DE REGISTROS MIGRADOS, SE INICIALIZA EN 0 Y SE VA ACTUALIZANDO A MEDIDA QUE SE PROCESAN LOS LOTES.
    total_migrado = 0
    # LISTA DE ARCHIVOS GENERADOS, SE UTILIZA PARA GUARDAR LAS RUTAS DE LOS ARCHIVOS CSV GENERADOS EN CADA LOTE,
    archivos_generados = []
    # NÚMERO DE LOTE, SE INICIALIZA EN 1 Y SE INCREMENTA EN CADA ITERACIÓN PARA IDENTIFICAR LOS ARCHIVOS GENERADOS.
    lote_num = 1
    
    # OBTENEMOS EL ÚLTIMO ID DE PACIENTES PARA SABER DESDE DÓNDE INICIAR LA EXTRACCIÓN EN ORACLE Y EVITAR DUPLICADOS.
    ultimo_id = control.obtener_ultimo_id(tabla)
    # REGISTRAMOS EN EL LOG QUE SE ESTÁ REANUDANDO LA EXTRACCIÓN DESDE EL ÚLTIMO ID OBTENIDO, 
    # INCLUYENDO EL NOMBRE DE LA TABLA Y EL ÚLTIMO ID PARA FACILITAR EL SEGUIMIENTO DEL PROGRESO.
    logging.info(f"Reanudando {tabla} desde ID: {ultimo_id}")

    # INICIAMOS UN BUCLE INFINITO PARA PROCESAR LOS LOTES DE DATOS HASTA QUE NO QUEDEN MÁS REGISTROS PARA EXTRAER.
    while True:
        # 1. EXTRACT - EXTRAEMOS UN LOTE DE DATOS DE LA TABLA PACIENTES DESDE ORACLE, INICIANDO DESDE 
        # EL ÚLTIMO ID OBTENIDO EN SQLITE PARA EVITAR DUPLICADOS. 
        df = reader.extraer_lote(tabla, pk, ultimo_id, settings.LOTE_SIZE)
        
        # SI EL DATAFRAME ESTÁ VACÍO, SIGNIFICA QUE NO QUEDAN MÁS REGISTROS PARA EXTRAER, POR LO QUE 
        # SE REGISTRA EN EL LOG QUE NO HAY MÁS DATOS PARA PROCESAR Y SE ROMPE EL BUCLE PARA FINALIZAR 
        # EL PROCESO DE EXTRACCIÓN. SI EL DATAFRAME NO ESTÁ VACÍO, SE CONTINÚA CON EL PROCESO DE TRANSFORMACIÓN Y CARGA. 
        if df.empty:
            # REGISTRAMOS EN EL LOG QUE NO HAY MÁS DATOS PARA PROCESAR EN LA TABLA ACTUAL, INCLUYENDO 
            # EL NOMBRE DE LA TABLA PARA FACILITAR EL SEGUIMIENTO DEL PROGRESO.
            logging.info(f"No hay más datos para procesar en {tabla}.")
            # ROMPEMOS EL BUCLE PARA FINALIZAR EL PROCESO DE EXTRACCIÓN, YA QUE NO QUEDAN MÁS REGISTROS PARA EXTRAER.
            break
            
        # 2. TRANSFORM - REALIZAMOS LA LIMPIEZA DE LOS DATOS EXTRAÍDOS UTILIZANDO EL MÉTODO limpiar_pacientes DE LA CLASE LimpiadorDatos,
        # QUE SE ENCARGA DE REALIZAR LAS TRANSFORMACIONES NECESARIAS PARA DEJAR LOS DATOS EN EL 
        # FORMATO ADECUADO ANTES DE GUARDARLOS EN CSV Y GENERAR LOS MANIFIESTOS. 
        # EL RESULTADO ES UN DATAFRAME LIMPIO QUE SE UTILIZA PARA LA CARGA EN CSV. 
        df_limpio = LimpiadorDatos.limpiar_pacientes(df)
        
        # 3. LOAD - GUARDAMOS EL LOTE LIMPIO EN UN ARCHIVO CSV UTILIZANDO EL MÉTODO guardar_lote DE LA CLASE CSVWriter,
        # QUE SE ENCARGA DE GUARDAR LOS LOTES EN ARCHIVOS CSV Y GENERAR LOS MANIFIESTOS EN FORMATO JSON. SE LE PASA 
        # EL DATAFRAME LIMPIO, EL NOMBRE DE LA TABLA Y EL NÚMERO DE LOTE PARA GENERAR UN NOMBRE DE ARCHIVO ÚNICO. 
        # EL MÉTODO RETORNA LA RUTA DEL ARCHIVO CSV GENERADO.
        ruta_csv = writer.guardar_lote(df_limpio, tabla, lote_num)
        # AGREGAMOS LA RUTA DEL ARCHIVO CSV GENERADO A LA LISTA DE ARCHIVOS GENERADOS PARA LUEGO INCLUIRLA EN EL MANIFIESTO DE LA TABLA.
        archivos_generados.append(ruta_csv)
        
        # ACTUALIZAMOS EL ÚLTIMO ID PROCESADO EN EL CONTROL DE EXTRACCIÓN PARA LA TABLA ACTUAL, UTILIZANDO EL MÁXIMO ID DEL DATAFRAME LIMPIO,
        # LO QUE PERMITE REANUDAR LA EXTRACCIÓN DESDE EL PUNTO CORRECTO EN LA PRÓXIMA EJECUCIÓN Y EVITAR DUPLICADOS.
        ultimo_id = int(df_limpio[pk].max())
        # ACTUALIZAMOS EL CONTROL DE EXTRACCIÓN CON EL NUEVO ÚLTIMO ID PROCESADO PARA LA TABLA ACTUAL, 
        # INCLUYENDO EL NOMBRE DE LA TABLA Y EL NUEVO ÚLTIMO ID PARA MANTENER UN REGISTRO ACTUALIZADO DEL PROGRESO DE LA EXTRACCIÓN.
        control.actualizar_ultimo_id(tabla, ultimo_id)
        
        # ACTUALIZAMOS EL TOTAL DE REGISTROS MIGRADOS SUMANDO LA CANTIDAD DE REGISTROS DEL DATAFRAME LIMPIO,
        # LO QUE PERMITE LLEVAR UN CONTROL DEL TOTAL DE REGISTROS PROCESADOS Y MIGRADOS A LO LARGO DE TODO EL PROCESO.
        total_migrado += len(df_limpio)
        # REGISTRAMOS EN EL LOG EL PROGRESO DE LA MIGRACIÓN, INCLUYENDO EL NOMBRE DE LA TABLA Y EL TOTAL DE REGISTROS 
        # PROCESADOS HASTA EL MOMENTO PARA FACILITAR EL SEGUIMIENTO DEL PROGRESO.
        logging.info(f"Progreso {tabla}: {total_migrado} registros procesados...")
        # INCREMENTAMOS EL NÚMERO DE LOTE PARA EL SIGUIENTE CICLO, LO QUE PERMITE GENERAR NOMBRES DE ARCHIVO ÚNICOS PARA CADA LOTE PROCESADO.   
        lote_num += 1

    # UNA VEZ QUE SE HAN PROCESADO TODOS LOS LOTES DE LA TABLA, SI EL TOTAL DE REGISTROS MIGRADOS 
    # ES MAYOR A 0, SE GENERA UN MANIFIESTO PARA LA TABLA UTILIZANDO EL MÉTODO generar_manifiesto DE LA CLASE CSVWriter QUE SE ENCARGA DE 
    # GUARDAR LOS LOTES EN ARCHIVOS CSV Y GENERAR LOS MANIFIESTOS EN FORMATO JSON, PASÁNDOLE EL NOMBRE DE LA TABLA, EL TOTAL 
    # DE REGISTROS MIGRADOS Y LA LISTA DE ARCHIVOS GENERADOS PARA INCLUIRLOS EN EL MANIFIESTO. 
    if total_migrado > 0:
        # GENERAMOS UN MANIFIESTO PARA LA TABLA UTILIZANDO EL MÉTODO generar_manifiesto DE LA CLASE CSVWriter, 
        # PASÁNDOLE EL NOMBRE DE LA TABLA, EL TOTAL DE REGISTROS MIGRADOS Y LA LISTA DE ARCHIVOS GENERADOS PARA INCLUIRLOS EN EL MANIFIESTO.
        writer.generar_manifiesto(tabla, total_migrado, archivos_generados)

# REGISTRAMOS EN EL LOG QUE EL PIPELINE ETL PARA LA TABLA ACTUAL HA FINALIZADO CORRECTAMENTE, INCLUYENDO EL 
# NOMBRE DE LA TABLA Y EL TOTAL DE REGISTROS MIGRADOS PARA FACILITAR EL SEGUIMIENTO DEL PROGRESO.
if __name__ == "__main__":
    # CONFIGURAMOS EL LOGGING PARA REGISTRAR LOS PROCESOS DE EXTRACCIÓN, TRANSFORMACIÓN Y CARGA, ASÍ COMO LA GENERACIÓN DE MANIFIESTOS,
    ejecutar_pipeline_completo()
