# IMPORTAMOS SYS PARA MANEJAR RUTAS
import sys
# DESDE PATHLIB IMPORTAMOS Path PARA MANEJAR RUTAS DE MANERA MÁS SENCILLA Y 
# PORTABLE ENTRE SISTEMAS OPERATIVOS         
from pathlib import Path

# AGREGAMOS EL DIRECTORIO ACTUAL AL PATH PARA PODER IMPORTAR LOS MÓDULOS DE EXTRACCIÓN Y CONTROL
sys.path.append(str(Path(__file__).resolve().parent))

# DESDE CONFIG IMPORTAMOS SETTINGS PARA OBTENER LAS CONFIGURACIONES NECESARIAS PARA LA EXTRACCIÓN Y CONTROL DE EXTRACCIÓN 
from config import settings
# DESDE EXTRACCIÓN IMPORTAMOS OracleReader PARA REALIZAR LA EXTRACCIÓN DE DATOS DESDE ORACLE Y ControlExtracción PARA MANEJAR EL CONTROL DE EXTRACCIÓN EN SQLITE 
from extraccion.oracle_reader import OracleReader
# DESDE EXTRACCIÓN CONTROL IMPORTAMOS ControlExtracción PARA MANEJAR EL CONTROL DE EXTRACCIÓN EN SQLITE
from extraccion.control import ControlExtraccion

# ESTA FUNCIÓN SE ENCARGA DE EJECUTAR UNA PRUEBA DE EXTRACCIÓN PARA VERIFICAR QUE 
# TODO ESTÉ CONFIGURADO CORRECTAMENTE Y QUE SE PUEDAN EXTRAER LOS DATOS DE ORACLE 
# Y CONTROLAR LA EXTRACCIÓN CON SQLITE. IMPRIME LOS RESULTADOS DE CADA PASO PARA FACILITAR LA VERIFICACIÓN.     
def ejecutar_prueba():
    # IMPRIMIMOS UN MENSAJE INFORMATIVO PARA INDICAR QUE SE ESTÁ INICIANDO LA PRUEBA DE EXTRACCIÓN   
    print("--- INICIANDO PRUEBA DE EXTRACCIÓN ---")
    
    # CONTROL DE EXTRACCIÓN (SQLITE) - OBTENEMOS EL ÚLTIMO ID DE PACIENTES PARA SABER DESDE DÓNDE INICIAR LA EXTRACCIÓN EN ORACLE Y EVITAR DUPLICADOS  
    control = ControlExtraccion(settings.CONTROL_DB_PATH)
    # OBTENEMOS EL ÚLTIMO ID DE PACIENTES PARA SABER DESDE DÓNDE INICIAR LA EXTRACCIÓN EN ORACLE Y EVITAR DUPLICADOS 
    ultimo_id = control.obtener_ultimo_id("PACIENTES")
    # IMPRIMIMOS EL ÚLTIMO ID DE PACIENTES OBTENIDO PARA VERIFICAR QUE SE ESTÁ OBTENIENDO CORRECTAMENTE
    print(f"Último ID de PACIENTES en SQLite: {ultimo_id}")

    # EXTRACCIÓN (ORACLE) - PROBAMOS LA CONEXIÓN Y EXTRAEMOS UN LOTE PEQUEÑO DE DATOS PARA VERIFICAR QUE SE PUEDEN EXTRAER CORRECTAMENTE  
    reader = OracleReader(settings.ORACLE_DSN)
    # PROBAMOS LA CONEXIÓN A ORACLE PARA VERIFICAR QUE ESTÁ CONFIGURADA CORRECTAMENTE Y SE PUEDE CONECTAR A LA BASE DE DATOS ANTES DE INTENTAR EXTRAER LOS DATOS 
    reader.probar_conexion()
    
    # DF ES EL DATAFRAME RESULTANTE DE LA EXTRACCIÓN DE UN LOTE PEQUEÑO DE DATOS DE LA TABLA PACIENTES DESDE ORACLE, 
    # INICIANDO DESDE EL ÚLTIMO ID OBTENIDO EN SQLITE PARA EVITAR DUPLICADOS. SE IMPRIMEN LOS PRIMEROS 5 REGISTROS PARA 
    # VERIFICAR QUE SE ESTÁN EXTRAÍENDO LOS DATOS CORRECTAMENTE. SI NO SE ENCUENTRAN REGISTROS, SE IMPRIME UN MENSAJE 
    # INDICANDO QUE NO SE ENCONTRARON REGISTROS, LO CUAL PUEDE SER NORMAL SI EL SCRIPT SQL AÚN NO HA CARGADO LOS DATOS EN ORACLE. 
    df = reader.extraer_lote("PACIENTES", "paciente_id", ultimo_id, lote_size=5)
    
    # SI EL DATAFRAME NO ESTÁ VACÍO, IMPRIMIMOS UN MENSAJE DE ÉXITO Y LOS PRIMEROS 5 REGISTROS PARA VERIFICAR 
    # QUE SE ESTÁN EXTRAÍENDO LOS DATOS CORRECTAMENTE. SI EL DATAFRAME ESTÁ VACÍO, IMPRIMIMOS UN MENSAJE INDICANDO QUE 
    # NO SE ENCONTRARON REGISTROS, LO CUAL PUEDE SER NORMAL SI EL SCRIPT SQL AÚN NO HA CARGADO LOS DATOS EN ORACLE.  
    if not df.empty:
        # IMPRIMIMOS UN MENSAJE DE ÉXITO Y LOS PRIMEROS 5 REGISTROS PARA VERIFICAR QUE SE ESTÁN EXTRAYENDO LOS DATOS CORRECTAMENTE  
        print("\n¡Extracción Exitosa! Aquí están los primeros 5 registros:")
        # IMPRIMIMOS LOS PRIMEROS 5 REGISTROS DEL DATAFRAME PARA VERIFICAR QUE SE ESTÁN EXTRAÍENDO LOS DATOS CORRECTAMENTE. 
        # SELECCIONAMOS SOLO LAS COLUMNAS RELEVANTES PARA LA VERIFICACIÓN.
        print(df.head())
        #print(df[['PACIENTE_ID', 'NOMBRE', 'APELLIDO', 'DOCUMENTO_IDENTIDAD']])
    # SINO SE ENCONTRARON REGISTROS, IMPRIMIMOS UN MENSAJE INDICANDO QUE NO SE ENCONTRARON REGISTROS, 
    # LO CUAL PUEDE SER NORMAL SI EL SCRIPT SQL AÚN NO HA CARGADO LOS DATOS EN ORACLE.
    else:
        print("No se encontraron registros. (¿Terminó de cargar el script SQL en Docker?)")

# SI ESTE ARCHIVO SE EJECUTA DIRECTAMENTE, SE LLAMA A LA FUNCIÓN ejecutar_prueba() PARA REALIZAR LA PRUEBA DE EXTRACCIÓN. 
if __name__ == "__main__":
    ejecutar_prueba()