# IMPORTAMOS SQLITE3 PARA MANEJAR LA BASE DE DATOS DE CONTROL Y LOGGING PARA REGISTRAR 
# LAS OPERACIONES DE EXTRACCIÓN. LA CLASE CONTROL_EXTRACCION SE ENCARGA DE GESTIONAR 
# EL CONTROL DE CARGAS, PERMITIENDO OBTENER Y ACTUALIZAR EL ÚLTIMO ID PROCESADO PARA 
# CADA TABLA. SE INICIALIZA LA BASE DE DATOS SI NO EXISTE Y SE PROPORCIONAN MÉTODOS PARA 
# OBTENER Y ACTUALIZAR LOS ID DE CONTROL.   
import sqlite3
# IMPORTAMOS LOGGING PARA REGISTRAR LAS OPERACIONES DE EXTRACCIÓN Y CONTROL DE CARGAS.
import logging

# CONFIGURAMOS EL LOGGING PARA MOSTRAR LA HORA Y EL MENSAJE DE CADA OPERACIÓN DE EXTRACCIÓN.
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')

# LA CLASE CONTROL_EXTRACCION SE ENCARGA DE GESTIONAR EL CONTROL DE CARGAS, PERMITIENDO 
# OBTENER Y ACTUALIZAR EL ÚLTIMO ID PROCESADO PARA CADA TABLA. 
# SE INICIALIZA LA BASE DE DATOS SI NO EXISTE Y SE PROPORCIONAN MÉTODOS PARA OBTENER Y ACTUALIZAR LOS ID DE CONTROL.
class ControlExtraccion:
    # EL MÉTODO __INIT__ INICIALIZA LA CLASE CON LA RUTA DE LA BASE DE DATOS Y LLAMA AL MÉTODO 
    # _INICIALIZAR_DB PARA CREAR LA TABLA DE CONTROL DE CARGAS SI NO EXISTE. 
    def __init__(self, db_path: str):
        # SE ASIGNA LA RUTA DE LA BASE DE DATOS A UN ATRIBUTO DE LA CLASE Y SE INICIALIZA LA BASE DE DATOS.
        self.db_path = db_path
        # SE LLAMA AL MÉTODO _INICIALIZAR_DB PARA CREAR LA TABLA DE CONTROL DE CARGAS SI NO EXISTE.
        self._inicializar_db()

    # EL MÉTODO _INICIALIZAR_DB CREA LA TABLA DE CONTROL DE CARGAS SI NO EXISTE, CON LOS CAMPOS 
    # "TABLA" COMO CLAVE PRIMARIA Y "ULTIMO_ID" PARA ALMACENAR EL ÚLTIMO ID PROCESADO PARA CADA TABLA.
    def _inicializar_db(self):
        # SE CONECTA A LA BASE DE DATOS Y EJECUTA LA SENTENCIA SQL PARA CREAR LA TABLA DE CONTROL DE CARGAS SI NO EXISTE.
        with sqlite3.connect(self.db_path) as conn:
            # SE EJECUTA LA SENTENCIA SQL PARA CREAR LA TABLA DE CONTROL DE CARGAS SI NO EXISTE, 
            # CON LOS CAMPOS "TABLA" COMO CLAVE PRIMARIA Y "ULTIMO_ID" PARA ALMACENAR EL ÚLTIMO ID PROCESADO PARA CADA TABLA.
            conn.execute("""
                CREATE TABLE IF NOT EXISTS control_cargas (
                    tabla TEXT PRIMARY KEY,
                    ultimo_id INTEGER
                )
            """)

    # EL MÉTODO OBTENER_ULTIMO_ID RECIBE EL NOMBRE DE LA TABLA Y DEVUELVE EL ÚLTIMO ID PROCESADO PARA ESA TABLA.
    def obtener_ultimo_id(self, tabla: str) -> int:
        # SE CONECTA A LA BASE DE DATOS Y EJECUTA LA SENTENCIA SQL PARA OBTENER EL ÚLTIMO ID PROCESADO PARA LA TABLA ESPECIFICADA.
        with sqlite3.connect(self.db_path) as conn:
            # SE EJECUTA LA SENTENCIA SQL PARA OBTENER EL ÚLTIMO ID PROCESADO PARA LA TABLA ESPECIFICADA Y SE DEVUELVE EL RESULTADO.
            cursor = conn.cursor()
            # SE EJECUTA LA SENTENCIA SQL PARA OBTENER EL ÚLTIMO ID PROCESADO PARA LA TABLA 
            # ESPECIFICADA Y SE DEVUELVE EL RESULTADO. SI NO HAY RESULTADO, SE DEVUELVE 0.
            cursor.execute("SELECT ultimo_id FROM control_cargas WHERE tabla = ?", (tabla,))
            # SE OBTIENE EL RESULTADO DE LA CONSULTA Y SE DEVUELVE EL ÚLTIMO ID 
            # PROCESADO PARA LA TABLA ESPECIFICADA. SI NO HAY RESULTADO, SE DEVUELVE 0. 
            resultado = cursor.fetchone()
            # SE DEVUELVE EL ÚLTIMO ID PROCESADO PARA LA TABLA ESPECIFICADA. SI NO HAY RESULTADO, SE DEVUELVE 0.
            return resultado[0] if resultado else 0
        
    # EL MÉTODO ACTUALIZACION_ULTIMO_ID RECIBE EL NOMBRE DE LA TABLA Y EL ÚLTIMO ID PROCESADO, 
    # Y ACTUALIZA O INSERTA ESTE VALOR EN LA BASE DE DATOS DE CONTROL DE CARGAS.
    def actualizar_ultimo_id(self, tabla: str, ultimo_id: int):
        # SE CONECTA A LA BASE DE DATOS Y EJECUTA LA SENTENCIA SQL PARA ACTUALIZAR O INSERTAR EL ÚLTIMO ID PROCESADO PARA LA TABLA ESPECIFICADA.
        with sqlite3.connect(self.db_path) as conn:
            # SE EJECUTA LA SENTENCIA SQL PARA ACTUALIZAR O INSERTAR EL ÚLTIMO ID PROCESADO PARA LA TABLA ESPECIFICADA.
            conn.execute("""
                INSERT OR REPLACE INTO control_cargas (tabla, ultimo_id) 
                VALUES (?, ?)
                ON CONFLICT(tabla) DO UPDATE SET ultimo_id = excluded.ultimo_id
            """, (tabla, ultimo_id))