# IMPORTAMOS PANDAS PARA MANEJAR LOS DATAFRAMES Y SQLALCHEMY PARA LA 
# CONEXIÓN A ORACLE Y LA EJECUCIÓN DE CONSULTAS. 
# TAMBIÉN CONFIGURAMOS EL LOGGING PARA REGISTRAR LOS EVENTOS DURANTE 
# LA EJECUCIÓN DEL CÓDIGOS. LA CLASE ORACLEREADER INICIALIZA LA CONEXIÓN A LA BASE DE DATOS,    
import pandas as pd
# DESDE SQLALCHEMY SE IMPORTA CREATE_ENGINE PARA CREAR LA CONEXIÓN Y TEXT PARA 
# EJECUTAR CONSULTAS PARAMETRIZADAS.
from sqlalchemy import create_engine, text
# CONFIGURAMOS EL LOGGING PARA REGISTRAR LOS EVENTOS DURANTE LA EJECUCIÓN DEL CÓDIGOS.
import logging

# CONFIGURAMOS EL LOGGING PARA REGISTRAR LOS EVENTOS DURANTE LA EJECUCIÓN DEL CÓDIGOS.
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')

# LA CLASE ORACLEREADER INICIALIZA LA CONEXIÓN A LA BASE DE DATOS, PROBAMOS LA 
# CONEXIÓN Y EXTRAEMOS LOS DATOS EN LOTES UTILIZANDO CONSULTAS PARAMETRIZADAS 
# PARA EVITAR INYECCIONES SQL Y MEJORAR EL RENDIMIENTO. LOS DATOS EXTRAÍDOS SE 
# DEVUELVEN COMO UN DATAFRAME DE PANDAS PARA SU POSTERIOR PROCESAMIENTO.
class OracleReader:
    # EL MÉTODO __INIT__ INICIALIZA LA CONEXIÓN A LA BASE DE DATOS UTILIZANDO EL DSN PROPORCIONADO. 
    def __init__(self, dsn: str):
        # SE INTENTA CREAR EL MOTOR DE ORACLE CON EL DSN PROPORCIONADO Y SE REGISTRA UN MENSAJE DE LOGGING.
        try:
           # SE CREA EL MOTOR DE ORACLE CON EL DSN PROPORCIONADO Y SE REGISTRA UN MENSAJE DE LOGGING.
           self.engine = create_engine(dsn)
           # SE REGISTRA UN MENSAJE DE LOGGING INDICANDO QUE EL MOTOR DE ORACLE SE INICIALIZÓ CORRECTAMENTE.
           logging.info("Motor de Oracle inicializando correctamente.")
        # SI HAY UN ERROR AL CONECTAR CON ORACLE, SE REGISTRA UN MENSAJE DE ERROR EN EL LOGGING Y SE LANZA LA EXCEPCIÓN.   
        except Exception as e:
            # SI HAY UN ERROR AL CONECTAR CON ORACLE, SE REGISTRA UN MENSAJE DE ERROR EN EL LOGGING Y SE LANZA LA EXCEPCIÓN.
            logging.error(f"Error al conectar con Oracle: {e}")
            # RAISE E PARA LANZAR LA EXCEPCIÓN Y PERMITIR QUE EL PROGRAMA MANEJE EL ERROR DE MANERA ADECUADA.
            raise e

    # EL MÉTODO PROBAR_CONEXION SE UTILIZA PARA VERIFICAR QUE LA CONEXIÓN A LA BASE DE DATOS SE HA ESTABLECIDO CORRECTAMENTE.    
    def probar_conexion(self):
        # SE ABRE UNA CONEXIÓN CON EL MOTOR DE ORACLE Y SE EJECUTA UNA CONSULTA SENCILLA PARA VERIFICAR LA CONEXIÓN.
        with self.engine.connect() as conn:
            # SE EJECUTA UNA CONSULTA SENCILLA PARA VERIFICAR LA CONEXIÓN Y SE REGISTRA EL RESULTADO EN EL LOGGING.
            resultado = conn.execute(text("SELECT 'Conexión Exitosa' FROM DUAL")).scalar()
            # SE REGISTRA EL RESULTADO DE LA PRUEBA DE CONEXIÓN EN EL LOGGING.
            logging.info(f"Prueba de conexión: {resultado}")

    # EL MÉTODO EXTRAER_LOTE SE UTILIZA PARA EXTRAER UN LOTE DE DATOS DE UNA TABLA ESPECÍFICA UTILIZANDO UNA CLAVE PRIMARIA Y UN TAMAÑO DE LOTE.
    def extraer_lote(self, tabla: str, pk: str, ultimo_id: int, lote_size: int) -> pd.DataFrame:
        # SE CONSTRUYE UNA CONSULTA SQL PARAMETRIZADA PARA EXTRAER UN LOTE DE DATOS DE LA TABLA 
        # ESPECÍFICA UTILIZANDO LA CLAVE PRIMARIA Y EL TAMAÑO DE LOTE PROPORCIONADOS.
        query = text(f"""
            SELECT * FROM {tabla}
            WHERE {pk} > :ultimo_id
            ORDER BY {pk} ASC
            FETCH NEXT :lote ROWS ONLY
        """)  

        # SE INTENTA ABRIR UNA CONEXIÓN CON EL MOTOR DE ORACLE Y EJECUTAR LA CONSULTA PARA EXTRAER EL LOTE DE DATOS.
        try: 
            # SE ABRE UNA CONEXIÓN CON EL MOTOR DE ORACLE Y SE EJECUTA LA CONSULTA PARA EXTRAER EL LOTE DE DATOS, PASANDO LOS PARÁMETROS NECESARIOS.
            with self.engine.connect() as conn:
                # SE EJECUTA LA CONSULTA PARA EXTRAER EL LOTE DE DATOS, PASANDO LOS PARÁMETROS NECESARIOS Y SE DEVUELVE EL RESULTADO COMO UN DATAFRAME DE PANDAS.
                df = pd.read_sql(query, conn, params={"ultimo_id": ultimo_id, "lote": lote_size})
                # RETORNAMOS EL DATAFRAME CON LOS DATOS EXTRAÍDOS DEL LOTE DE LA TABLA ESPECÍFICA.   
                return df
        # SI HAY UN ERROR AL EXTRAER EL LOTE DE DATOS, SE REGISTRA UN MENSAJE DE ERROR EN EL LOGGING Y SE LANZA LA EXCEPCIÓN.    
        except Exception as e:
            # SI HAY UN ERROR AL EXTRAER EL LOTE DE DATOS, SE REGISTRA UN MENSAJE DE ERROR EN EL LOGGING Y SE LANZA LA EXCEPCIÓN.
            logging.error(f"Error extrayendo lote de la tabla {tabla}: {e}")
            # RAISE E PARA LANZAR LA EXCEPCIÓN Y PERMITIR QUE EL PROGRAMA MANEJE EL ERROR DE MANERA ADECUADA.
            raise e                    