# IMPORTAMOS OS PARA MANEJAR RUTAS Y PATHLIB PARA UNA MANEJO MÁS SENCILLO DE LAS RUTAS DE 
# LOS ARCHIVOS Y DIRECTORIOS EN NUESTRO PROYECTO. DEFINIMOS LAS VARIABLES DE CONFIGURACIÓN PARA 
# LA CONEXIÓN A LA BASE DE DATOS ORACLE, ASÍ COMO LAS RUTAS PARA LOS ARCHIVOS DE SALIDA Y CONTROL DE EXTRACCIÓN. 
# TAMBIÉN CREAMOS EL DIRECTORIO DE SALIDA SI NO EXISTE Y DEFINIMOS EL TAMAÑO DEL LOTE PARA LA EXTRACCIÓN DE DATOS.
import os
# DESDE PATHLIB IMPORTAMOS PATH PARA MANEJAR LAS RUTAS DE LOS ARCHIVOS Y DIRECTORIOS DE MANERA MÁS SENCILLA Y LEGIBLE.
from pathlib import Path

# DEFINIMOS LA RUTA BASE DEL PROYECTO, EL DIRECTORIO DE SALIDA PARA LOS ARCHIVOS 
# CSV Y LA RUTA PARA LA BASE DE DATOS DE CONTROL DE EXTRACCIÓN.
BASE_DIR = Path(__file__).resolve().parent.parent
# DEFINIMOS LA RUTA DE SALIDA PARA LOS ARCHIVOS CSV Y LA RUTA PARA LA BASE DE DATOS DE CONTROL DE EXTRACCIÓN.
OUTPUT_DIR = BASE_DIR / "output_csv"
# DEFINIMOS LA RUTA PARA LA BASE DE DATOS DE CONTROL DE EXTRACCIÓN, QUE SE UTILIZARÁ PARA SEGUIR 
# EL PROGRESO DE LA EXTRACCIÓN DE DATOS.
CONTROL_DB_PATH = BASE_DIR / "extraccion" / "control_extraccion.db"

# CREAMOS EL DIRECTORIO DE SALIDA SI NO EXISTE, ASEGURÁNDONOS DE QUE TODOS LOS PADRES DEL DIRECTORIO 
# TAMBIÉN SEAN CREADOS SI ES NECESARIO.
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# CONFIGURACIÓN DE LA CONEXIÓN A LA BASE DE DATOS ORACLE, INCLUYENDO EL USUARIO, CONTRASEÑA, HOST, PUERTO Y NOMBRE DEL SERVICIO.
ORACLE_USER = "hospital_admin"
ORACLE_PASSWORD = "hospital123"
ORACLE_HOST = "localhost"
ORACLE_PORT = "1521"
ORACLE_SERVICE = "XEPDB1"

# DEFINIMOS LA CADENA DE CONEXIÓN PARA LA BASE DE DATOS ORACLE UTILIZANDO EL FORMATO REQUERIDO POR SQLALCHEMY, INCLUYENDO EL USUARIO, 
# CONTRASEÑA, HOST, PUERTO Y NOMBRE DEL SERVICIO. 
ORACLE_DSN = f"oracle+oracledb://{ORACLE_USER}:{ORACLE_PASSWORD}@{ORACLE_HOST}:{ORACLE_PORT}/?service_name={ORACLE_SERVICE}"

# DEFINIMOS EL TAMAÑO DEL LOTE PARA LA EXTRACCIÓN DE DATOS, LO QUE PERMITE CONTROLAR CUÁNTAS FILAS SE EXTRAEN EN CADA ITERACIÓN DEL PROCESO DE EXTRACCIÓN.
LOTE_SIZE = 10000